### ISSUE TITLE
Status icon for Homey Button

### ISSUE THREAD

**Issue by dansity** [runely/remootio-homey#15]
Hello! Thank you for the Homey app!
Is it possible to include status indicator icon about the input pins on remootio? I have a magnetic switch to check if the gate is open (connected to input1) and some indication on the status would be great in the Homey app, especially on the button itself.

**Comment by runely** [comment]
Status icon on the tile for capability `garagedoor_closed` isn't availble from Homey. [I've requested it a while back...](https://github.com/athombv/homey-apps-sdk-issues/issues/235)

Status indicators on the device page itself for the inputs would be handy. I'll look into it

**Comment by dansity** [comment]
Just wondering (without looking into your code). Can you use any other boolean capability and display an exclamation mark on the button? The one displayed for the motion sensor would be totally fine, Shelly relays and Fibaro relays use the same mark for the switch input. https://apps.developer.homey.app/the-basics/devices/capabilities#device-indicators-and-custom-capabilities

**Comment by runely** [comment]
After looking into this a bit, I struggle to see what to gain by adding indicators for the `input1` and/or `input2`.

One of the inputs are to be used with the **gate status sensor** which tells if the gate/garagedoor is open/closed. The Remootio will send events on status changes for this sensor.

The other input can be used for the **doorbell** or a **manual control button** for the gate/garagedoor. You can of course connect whatever you want to this input as long as the circuit will be closed when something happens, but this input will only register when the circuit is closed (never when it's open again). The Remootio will send events when this circuit has closed and pass along the state of the **gate status sensor**.
So since this doesn't have it's own status, I feel it would be very missleading/confusing to show the state of the **gate status sensor** when you were expecting the status of what's connected to this input.

If you see another use case for this, please let me know
