### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by jaccoh** [runely/remootio-homey#19]
Lately I've been getting connection issues. The Remootio device in Homey is offline a lot. Ofcourse I've been testing wifi and I will keep trying to improve it, however the signal is great and the Remootio app itself is always able to connect via wifi.

Is there anything I can research? Is there maybe a timeout issue? Can I see logging somewhere?

**Comment by runely** [comment]
Have you read the [troubleshoot](https://github.com/runely/remootio-homey#troubleshooting) section?

As of now there's no way for you to see the logs. It's only logged to the console.

Can you try to reconnect to your device and when it's disconnected send me a diagnostics report and I'll take a look

**Comment by jaccoh** [comment]
I have read it. And also aware of the single wifi connection. I emailed Remootio about it .. maybe they are wiling to up that number? Also I was thinking, could make like a ws proxy in nginx and do a DNS trick as well….

The only things I am wondering about:

- but I guess the app doesn’t use the API, why can the app always connect?
- could Homey maybe use Bluetooth so the Wifi issue is avoided?

**Comment by runely** [comment]
The app can always connect, as you said, because it doesn't use the WebSocket API.

Remootio has only released documentation for connecting through the WebSocket API (WiFi).

If you still have connection problems, **and you are sure the Remootio device is connected to the same WiFi network as your homey**, please reboot the Remootio device to make sure no one else is using the WebSocket API and see if the homey app then connects.

Feel free to send a diagnostics report from the homey app and I will take a look at the logs

**Comment by jaccoh** [comment]
For now you can close it I guess ..On 2 Sep 2022, at 20:24, Rune Moskvil Lyngås ***@***.***> wrote:﻿
The app can always connect, as you said, because it doesn't use the WebSocket API.
Remootio has only released documentation for connecting through the WebSocket API (WiFi).
If you still have connection problems, and you are sure the Remootio device is connected to the same WiFi network as your homey, please reboot the Remootio device to make sure no one else is using the WebSocket API and see if the homey app then connects.
Feel free to send a diagnostics report from the homey app and I will take a look at the logs
